version: '3.8'


services:

  # db:
  #   image: postgres:14.3
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   container_name: ${DB_NAME}
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data

  app:
    # depends_on:
    #   - db
    container_name: Teslo-shop
    image: hectortyt/teslo-shop
    ports:
      - ${PORT}:3000
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}

# volumes:
#   postgres-db:
#     external: false


